version: '3.2'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    restart: always
  
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./public:/var/www/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: always